JavaScriptDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('ads.urls')),
    path('admin/', admin.site.urls),
]

ads/urls.py
from django.urls import path, reverse

from ads import views

app_name = 'ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),

    path('ad/create/', views.AdCreateView.as_view(success_url=reverse('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update/,', views.AdUpdateView.as_view(success_url=reverse('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete/', views.AdDeleteView.as_view(success_url=reverse('ads:all')), name='ad_delete'),

    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
]

ads/models.py
from django.conf import settings
from django.core.validators import MinLengthValidator
from django.db import models

# Create your models here.

class Ad(models.Model):
    title = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, 'Title must be greater than 2 characters')]
    )
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # Picture
    picture = models.BinaryField(null=True, editable=True)
    content_type = models.CharField(
        max_length=256,
        null=True,
        help_text='The MIMEType of the file'
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

ads/forms.py
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.forms import ModelForm, FileField
from .humanize import naturalsize
from .models import Ad


class CreateForm(ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_uplaod_limit_text = naturalsize(max_upload_limit)

    picture = FileField(
        required=False,
        label='File to upload <=' + str(max_uplaod_limit_text)
    )
    upload_field_name = 'picture'

    class Meta:
        model = Ad
        fields = ['title', 'text', 'picture']

    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if not pic: return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', 'File must be <' + self.max_uplaod_limit_text + 'bytes')

    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        f = instance.picture
        if isinstance(f, InMemoryUploadedFile):
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr

        if commit:
            instance.save()

        return instance

ads/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.urls import reverse_lazy
from django.views import View

from ads.models import Ad
from .forms import CreateForm
from .owner import *


class AdListView(OwnerListView):
    model = Ad
    template_name = 'list.html'

class AdDetailView(OwnerDetailView):
    model = Ad
    template_name = 'detail.html'

class AdCreateView(LoginRequiredMixin, View):
    template_name = 'form.html'
    success_url = reverse_lazy('ads:all')

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}

        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        pic = form.save(commit=False)
        pic.owner = self.request.user
        pic.save()
        return redirect(self.success_url)


class AdUpdateView(LoginRequiredMixin, View):
    template_name = 'form.html'
    success_url = reverse_lazy('ads:all')

    def get(self, request, pk=None):
        pic = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(instance=pic)
        ctx = {'form': form}

        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        pic = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=pic)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        form.save(commit=False)
        pic.save()

        return redirect(self.success_url)


class AdDeleteView(OwnerDeleteView):
    model = Ad
    template_name = 'delete.html'

def stream_file(request, pk):
    pic = get_object_or_404(Ad, id=pk)
    response = HttpResponse()
    response['Content-Type'] = request.content_type
    response['Content-Length'] = len(pic.picture)
    response.write(pic.picture)
    return response

templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<!-- Replace this value (42-42) with the one provided by the autograder -->
<meta name="dj4e" content="9d63484abb477c97640154d40595a3bb">

{#<meta name="dj4e-code" content="42160165394730">#}

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<meta name="dj4e-version" content="2020-10-01">

{% block head %} {% endblock %}

</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

templates/delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Delete Pic</h1>

<p>Are you sure you want to delete the pic: {{ pic }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

templates/detail.html
{% extends "base_bootstrap.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% endblock %}
{% block content %}
{% if pic.content_type %}
<div id="overlay" class="overlay" style="text-align: center;"
   onclick="document.getElementById('overlay').style.display = 'none';" >
<img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'ads:ad_picture' pic.id %}">
</div>
{% endif %}
<span style="float: right;">
({{ pic.updated_at|naturaltime }})
{% if pic.owner == user %}
<a href="{% url 'ads:ad_update' pic.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'ads:ad_delete' pic.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ pic.title }}</h1>
{% if pic.content_type %}
<img style="float:right; max-width:50%;" src="{% url 'ads:ad_picture' pic.id %}"
    onclick="document.getElementById('overlay').style.display = 'block';">
{% endif %}
<p>
{{ pic.text }}
</p>
<p>
</p>
<p>
<a href="{% url 'ads:all' %}">All pics</a>
</p>
{% endblock %}

templates/form.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'ads:all' %}';return false;">
  </form>
</p>
<!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}

templates/list.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Pics</h1>
<p>
{% if pic_list %}
<ul>
  {% for pic in pic_list %}
    <li>
        <a href="{% url 'ads:ad_detail'  pic.id %}">{{ pic.title }}</a>
        {% if pic.owner == user %}
        (<a href="{% url 'ads:ad_update' pic.id %}">Edit</a> |
        <a href="{% url 'ads:ad_delete' pic.id %}">Delete</a>)
        {% endif %}
        </p>
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no pics in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'ads:ad_create' %}">Add an Pic</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'ads:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'ads:all' %}">Login</a>
{% endif %}
</p>
{% endblock %}